class InsiteDataObject {
  getToken(): string {
    return 'eyJhbGciOiJIUzUxMiJ9.eyJ3ZWJSb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IlRlc3QiLCJsYXN0TmFtZSI6IlVzZXIiLCJwYXNzd29yZFJlc2V0IjpmYWxzZSwiZW52IjoiTE9DQUwiLCJleHAiOjE2NTk1NjM5NDEsInVzZXJJZCI6NiwiaWF0IjoxNjU5NTQ1OTQxLCJlbWFpbCI6InRlc3RAdXNlci5jb20ifQ.LpzHXld-0KnFeZckcE3iFO8dk49kQMmZkXaY75GhcW3hbIsvy5-fwtfFHoCQGfoRfo7WatLGp15nWLi64c2vEA';
  }
}

export const InisteTestData = new InsiteDataObject();
