# Build UI library.

name: Insitekit UI Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Insite Kit Library Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: Install Library Dependencies
        run: npm install --legacy-peer-deps
      - name: Run Test
        run: npm run test:headless
