name: Publish Tag
on:
  workflow_run:
    workflows: ["Release Library"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Library Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ./projects/insite-kit
      - name: Create Tag and Release
        id: versionBump
        uses: hydroponics-system/version-release@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.package-version.outputs.current-version}}
      - name: Publish Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versionBump.outputs.tag }}
          release_name: ${{ steps.versionBump.outputs.release_name }}
          body: ${{ steps.versionBump.outputs.body }}
          draft: false
          prerelease: false
