# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release Library

on:
  workflow_dispatch:

jobs:
  build:
    name: Insite Kit Library Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: Install Library Dependencies
        run: npm install --legacy-peer-deps
      - name: Run Build
        run: npm run build
      - name: Publish Package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./dist/insite-kit/package.json
